### ISSUE TITLE
Retriever SEGFAULTs if copied or assigned

### ISSUE THREAD

**Issue by mkoval** [ros/resource_retriever#1]
`Retriever` constructor creates a `CURL` handle by raw pointer and deletes it in the destructor. However, the class violates the [Rule of Three](https://en.wikipedia.org/wiki/Rule_of_three_%28C%2B%2B_programming%29) because there are no user-defined copy or assignment operators defined. This leads to a double-free on the `CURL` handle if the default implementations are invoked.

This could be resolved by either: (1) defining these to perform a deep copy on the `CURL` handle or (2) declaring them as private to disable generation of the default methods.

**Comment by jackieokay** [comment]
I'll try to fix this before making a release of resource_retriever for Kinetic (which is blocking several other packages).

**Comment by jackieokay** [comment]
I would like to disable the copy constructor, which I believe is an ABI change (changing the visibility of an implicitly declared function). So the fix will probably not be released into Indigo. Defining the copy constructor will mean adding a public accessor for the CURL pointer, which doesn't seem consistent with the original implementation since the CURL pointer is for caching purposes and is not otherwise exposed, but I believe this path would not break ABI. @mkoval if you're still invested in this issue, do you have a preference?

**Comment by jackieokay** [comment]
#2 has been merged and I have submitted the rosdistro PR to get this released into Kinetic.

**Comment by mkoval** [comment]
I'm fine with making the class non-copyable. I believe you're correct about this being an ABI change - it makes sense to release it in Kinectic.
